CREATE DATABASE IF NOT EXISTS RetailDB;
USE RetailDB;

-- 1. Reference Tables without foreign keys
CREATE TABLE CATEGORY (
    CategoryId INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(255) NOT NULL,
    Description TEXT
);

CREATE TABLE BRAND (
    BrandId INT AUTO_INCREMENT PRIMARY KEY,
    BrandName VARCHAR(255) NOT NULL,
    Description TEXT
);

CREATE TABLE PACKAGING (
    PackagingId INT AUTO_INCREMENT PRIMARY KEY,
    PackagingType VARCHAR(255) NOT NULL,
    Size VARCHAR(50),
    ExtraPrice DECIMAL(10, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE USER (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Phone VARCHAR(50),
    Address TEXT,
    Role VARCHAR(50) NOT NULL DEFAULT 'Customer',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COUPON (
    CouponId INT AUTO_INCREMENT PRIMARY KEY,
    CouponCode VARCHAR(50) NOT NULL UNIQUE,
    DiscountType VARCHAR(50) NOT NULL,
    DiscountValue DECIMAL(10, 2) NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Tables with foreign keys to reference tables
CREATE TABLE PRODUCT (
    ProductId INT AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Description TEXT,
    BasePrice DECIMAL(10, 2) NOT NULL,
    CategoryId INT,
    BrandId INT,
    PackagingId INT,
    StockQuantity INT NOT NULL DEFAULT 0,
    IsAvailable BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryId) REFERENCES CATEGORY(CategoryId) ON DELETE SET NULL,
    FOREIGN KEY (BrandId) REFERENCES BRAND(BrandId) ON DELETE SET NULL,
    FOREIGN KEY (PackagingId) REFERENCES PACKAGING(PackagingId) ON DELETE SET NULL
);

CREATE TABLE CART (
    CartId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES USER(UserId) ON DELETE CASCADE
);

CREATE TABLE `ORDER` (
    OrderId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(10, 2) NOT NULL,
    OrderStatus VARCHAR(50) NOT NULL,
    DeliveryAddress TEXT,
    PaymentStatus VARCHAR(50) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES USER(UserId) ON DELETE CASCADE
);

CREATE TABLE LOYALTY_ACCOUNT (
    LoyaltyAccountId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT UNIQUE,
    PointBalance INT NOT NULL DEFAULT 0,
    LastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES USER(UserId) ON DELETE CASCADE
);

-- 3. Dependent Tables (Items & Transactions)
CREATE TABLE CART_ITEM (
    CartItemId INT AUTO_INCREMENT PRIMARY KEY,
    CartId INT,
    ProductId INT,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10, 2) NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (CartId) REFERENCES CART(CartId) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES PRODUCT(ProductId) ON DELETE CASCADE
);

CREATE TABLE ORDER_ITEM (
    OrderItemId INT AUTO_INCREMENT PRIMARY KEY,
    OrderId INT,
    ProductId INT,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10, 2) NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES `ORDER`(OrderId) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES PRODUCT(ProductId) ON DELETE RESTRICT
);

CREATE TABLE INVENTORY_TRANSACTION (
    TransactionId INT AUTO_INCREMENT PRIMARY KEY,
    ProductId INT,
    QuantityChanged INT NOT NULL,
    TransactionType VARCHAR(50) NOT NULL,
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Remarks TEXT,
    FOREIGN KEY (ProductId) REFERENCES PRODUCT(ProductId) ON DELETE CASCADE
);

CREATE TABLE ORDER_COUPON (
    OrderCouponId INT AUTO_INCREMENT PRIMARY KEY,
    OrderId INT,
    CouponId INT,
    DiscountApplied DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES `ORDER`(OrderId) ON DELETE CASCADE,
    FOREIGN KEY (CouponId) REFERENCES COUPON(CouponId) ON DELETE CASCADE
);

CREATE TABLE EMAIL_NOTIFICATION (
    EmailNotificationId INT AUTO_INCREMENT PRIMARY KEY,
    OrderId INT,
    UserId INT,
    EmailType VARCHAR(50) NOT NULL,
    SentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES `ORDER`(OrderId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES USER(UserId) ON DELETE CASCADE
);
